---
includes:
  # System-level requirements
  - docs/reqstream/reqstream/reqstream.yaml
  # Program unit
  - docs/reqstream/reqstream/program.yaml
  # Cli subsystem
  - docs/reqstream/reqstream/cli/cli.yaml
  - docs/reqstream/reqstream/cli/context.yaml
  # Modeling subsystem
  - docs/reqstream/reqstream/modeling/modeling.yaml
  - docs/reqstream/reqstream/modeling/requirements.yaml
  # Tracing subsystem
  - docs/reqstream/reqstream/tracing/tracing.yaml
  - docs/reqstream/reqstream/tracing/trace-matrix.yaml
  # SelfTest subsystem
  - docs/reqstream/reqstream/self-test/self-test.yaml
  - docs/reqstream/reqstream/self-test/validation.yaml
  # Platform support and OTS software
  - docs/reqstream/reqstream/platform-requirements.yaml
  - docs/reqstream/ots/mstest.yaml
  - docs/reqstream/ots/buildmark.yaml
  - docs/reqstream/ots/versionmark.yaml
  - docs/reqstream/ots/sarifmark.yaml
  - docs/reqstream/ots/sonarmark.yaml
  - docs/reqstream/ots/reviewmark.yaml
