package ReqStream {
    part def Validation {
        doc /* Self-validation test runner. */

        comment sourceRef /* Source: src/DemaConsulting.ReqStream/SelfTest/Validation.cs */
        comment testRef /* Test: test/DemaConsulting.ReqStream.Tests/SelfTest/ValidationTests.cs */
        comment designRef /* Design: docs/design/reqstream/self-test/validation.md */
        comment verificationRef /* Verification: docs/verification/reqstream/self-test/validation.md */
        comment reqRef /* Requirements: docs/reqstream/reqstream/self-test/validation.yaml */
    }
}
