package ReqStream {
    part def CliSubsystem {
        doc /* Command-line argument parsing and I/O ownership. */

        comment testRef /* Test: test/DemaConsulting.ReqStream.Tests/Cli/CliTests.cs */
        comment designRef /* Design: docs/design/reqstream/cli.md */
        comment verificationRef /* Verification: docs/verification/reqstream/cli.md */
        comment reqRef /* Requirements: docs/reqstream/reqstream/cli.yaml */

        part context : Context;
    }
}
