package ReqStream {
    part def Program {
        doc /* Entry point and execution orchestrator. */

        comment sourceRef /* Source: src/DemaConsulting.ReqStream/Program.cs */
        comment testRef /* Test: test/DemaConsulting.ReqStream.Tests/ProgramTests.cs */
        comment designRef /* Design: docs/design/reqstream/program.md */
        comment verificationRef /* Verification: docs/verification/reqstream/program.md */
        comment reqRef /* Requirements: docs/reqstream/reqstream/program.yaml */
    }
}
