package ReqStream {
    part def LintIssue {
        doc /* Lint issue severity and data model. */

        comment sourceRef /* Source: src/DemaConsulting.ReqStream/Modeling/LintIssue.cs */
        comment testRef /* Test: test/DemaConsulting.ReqStream.Tests/Modeling/LintIssueTests.cs */
        comment designRef /* Design: docs/design/reqstream/modeling/lint-issue.md */
        comment verificationRef /* Verification: docs/verification/reqstream/modeling/lint-issue.md */
        comment reqRef /* Requirements: docs/reqstream/reqstream/modeling/lint-issue.yaml */
    }
}
