package ReqStream {
    part def Requirement {
        doc /* Single requirement with ID, title, and test links. */

        comment sourceRef /* Source: src/DemaConsulting.ReqStream/Modeling/Requirement.cs */
        comment testRef /* Test: test/DemaConsulting.ReqStream.Tests/Modeling/RequirementTests.cs */
        comment designRef /* Design: docs/design/reqstream/modeling/requirement.md */
        comment verificationRef /* Verification: docs/verification/reqstream/modeling/requirement.md */
        comment reqRef /* Requirements: docs/reqstream/reqstream/modeling/requirement.yaml */
    }
}
