package ReqStream {
    part def Section {
        doc /* Named group of requirements within a document. */

        comment sourceRef /* Source: src/DemaConsulting.ReqStream/Modeling/Section.cs */
        comment testRef /* Test: test/DemaConsulting.ReqStream.Tests/Modeling/SectionTests.cs */
        comment designRef /* Design: docs/design/reqstream/modeling/section.md */
        comment verificationRef /* Verification: docs/verification/reqstream/modeling/section.md */
        comment reqRef /* Requirements: docs/reqstream/reqstream/modeling/section.yaml */
    }
}
